import Joi from 'joi';

export const createBannerValidation = Joi.object({
    title: Joi.string().trim().required().max(255).messages({
      'any.required': 'Title is required',
      'string.max': 'Title must be at most 255 characters',
    }),
    subtitle: Joi.string().trim().optional().max(500).allow(null, ''),
    description: Joi.string().trim().optional().allow(null, ''),
    type: Joi.string().valid('IMAGE', 'VIDEO', 'HTML').required().messages({
      'any.only': 'Type must be one of IMAGE, VIDEO, HTML',
      'any.required': 'Type is required',
    }),
    status: Joi.string().valid('DRAFT', 'ACTIVE', 'PAUSED', 'EXPIRED', 'ARCHIVED').default('DRAFT').optional(),
    placement: Joi.string().valid(
      'HOME_TOP', 'HOME_MIDDLE', 'HOME_BOTTOM', 
      'CATEGORY_PAGE', 'PRODUCT_PAGE', 'CART_PAGE', 
      'CHECKOUT_PAGE', 'APP_HOME', 'APP_SPLASH'
    ).required().messages({
      'any.only': 'Invalid placement value',
      'any.required': 'Placement is required',
    }),
    imageUrl: Joi.string().uri().optional().allow(null, ''),
    mobileImageUrl: Joi.string().uri().optional().allow(null, ''),
    videoUrl: Joi.string().uri().optional().allow(null, ''),
    altText: Joi.string().trim().optional().max(255).allow(null, ''),
    ctaText: Joi.string().trim().optional().max(100).allow(null, ''),
    ctaUrl: Joi.string().uri().optional().allow(null, ''),
    productId: Joi.string().trim().optional().allow(null, ''),
    categoryId: Joi.string().trim().optional().allow(null, ''),
    brandId: Joi.string().trim().optional().allow(null, ''),
    offerCode: Joi.string().trim().optional().max(50).allow(null, ''),
    offerText: Joi.string().trim().optional().max(255).allow(null, ''),
    discountPercent: Joi.number().precision(2).min(0).max(100).optional().allow(null),
    discountAmount: Joi.number().precision(2).min(0).optional().allow(null),
    visibleToRoles: Joi.array().items(Joi.string()).optional().default([]),
    visibleCities: Joi.array().items(Joi.string()).optional().default([]),
    visibleStates: Joi.array().items(Joi.string()).optional().default([]),
    visibleDevices: Joi.array().items(Joi.string().valid('WEB', 'ANDROID', 'IOS')).optional().default([]),
    startAt: Joi.date().iso().optional().allow(null),
    endAt: Joi.date().iso().min(Joi.ref('startAt')).optional().allow(null),
    displayOrder: Joi.number().integer().min(0).default(0).optional(),
    metadata: Joi.object().optional().allow(null),
    createdBy: Joi.string().trim().optional().allow(null, ''),
});

export const updateBannerValidation = Joi.object({
  title: Joi.string().trim().optional().max(255),
  subtitle: Joi.string().trim().optional().max(500).allow(null, ''),
  description: Joi.string().trim().optional().allow(null, ''),
  type: Joi.string().valid('IMAGE', 'VIDEO', 'HTML').optional(),
  status: Joi.string().valid('DRAFT', 'ACTIVE', 'PAUSED', 'EXPIRED', 'ARCHIVED').optional(),
  placement: Joi.string().valid(
    'HOME_TOP', 'HOME_MIDDLE', 'HOME_BOTTOM', 
    'CATEGORY_PAGE', 'PRODUCT_PAGE', 'CART_PAGE', 
    'CHECKOUT_PAGE', 'APP_HOME', 'APP_SPLASH'
  ).optional(),
  imageUrl: Joi.string().uri().optional().allow(null, ''),
  mobileImageUrl: Joi.string().uri().optional().allow(null, ''),
  videoUrl: Joi.string().uri().optional().allow(null, ''),
  altText: Joi.string().trim().optional().max(255).allow(null, ''),
  ctaText: Joi.string().trim().optional().max(100).allow(null, ''),
  ctaUrl: Joi.string().uri().optional().allow(null, ''),
  productId: Joi.string().trim().optional().allow(null, ''),
  categoryId: Joi.string().trim().optional().allow(null, ''),
  brandId: Joi.string().trim().optional().allow(null, ''),
  offerCode: Joi.string().trim().optional().max(50).allow(null, ''),
  offerText: Joi.string().trim().optional().max(255).allow(null, ''),
  discountPercent: Joi.number().precision(2).min(0).max(100).optional().allow(null),
  discountAmount: Joi.number().precision(2).min(0).optional().allow(null),
  visibleToRoles: Joi.array().items(Joi.string()).optional(),
  visibleCities: Joi.array().items(Joi.string()).optional(),
  visibleStates: Joi.array().items(Joi.string()).optional(),
  visibleDevices: Joi.array().items(Joi.string().valid('WEB', 'ANDROID', 'IOS')).optional(),
  startAt: Joi.date().iso().optional().allow(null),
  endAt: Joi.date().iso().min(Joi.ref('startAt')).optional().allow(null),
  displayOrder: Joi.number().integer().min(0).optional(),
  metadata: Joi.object().optional().allow(null),
  createdBy: Joi.string().trim().optional().allow(null, ''),
});

