import Joi from 'joi';

export const createBannerValidation = Joi.object({
    title: Joi.string().required().max(255),
    subtitle: Joi.string().optional().max(500),
    description: Joi.string().optional(),
    type: Joi.string().valid('IMAGE', 'VIDEO', 'HTML').required(),
    status: Joi.string().valid('DRAFT', 'ACTIVE', 'PAUSED', 'EXPIRED', 'ARCHIVED').required(),
    placement: Joi.string().valid(
      'HOME_TOP', 'HOME_MIDDLE', 'HOME_BOTTOM', 
      'CATEGORY_PAGE', 'PRODUCT_PAGE', 'CART_PAGE', 
      'CHECKOUT_PAGE', 'APP_HOME', 'APP_SPLASH'
    ).required(),
    imageUrl: Joi.string().uri().optional(),
    mobileImageUrl: Joi.string().uri().optional(),
    videoUrl: Joi.string().uri().optional(),
    altText: Joi.string().optional().max(255),
    ctaText: Joi.string().optional().max(100),
    ctaUrl: Joi.string().uri().optional(),
    productId: Joi.string().optional(),
    categoryId: Joi.string().optional(),
    brandId: Joi.string().optional(),
    vendorId: Joi.string().optional(),
    offerCode: Joi.string().optional().max(50),
    offerText: Joi.string().optional().max(255),
    discountPercent: Joi.number().precision(2).min(0).max(100).optional(),
    discountAmount: Joi.number().precision(2).min(0).optional(),
    visibleToRoles: Joi.array().items(Joi.string()).optional(),
    visibleCities: Joi.array().items(Joi.string()).optional(),
    visibleStates: Joi.array().items(Joi.string()).optional(),
    visibleDevices: Joi.array().items(Joi.string()).optional(),
    startAt: Joi.date().optional(),
    endAt: Joi.date().optional(),
    displayOrder: Joi.number().integer().min(0).optional(),
    metadata: Joi.object().optional(),
    createdBy: Joi.string().optional(),
});

export const updateBannerValidation = Joi.object({
  title: Joi.string().optional().max(255),
  subtitle: Joi.string().optional().max(500),
  description: Joi.string().optional(),
  type: Joi.string().valid('IMAGE', 'VIDEO', 'HTML').optional(),
  status: Joi.string().valid('DRAFT', 'ACTIVE', 'PAUSED', 'EXPIRED', 'ARCHIVED').optional(),
  placement: Joi.string().valid(
    'HOME_TOP', 'HOME_MIDDLE', 'HOME_BOTTOM', 
    'CATEGORY_PAGE', 'PRODUCT_PAGE', 'CART_PAGE', 
    'CHECKOUT_PAGE', 'APP_HOME', 'APP_SPLASH'
  ).optional(),
  imageUrl: Joi.string().uri().optional(),
  mobileImageUrl: Joi.string().uri().optional(),
  videoUrl: Joi.string().uri().optional(),
  altText: Joi.string().optional().max(255),
  ctaText: Joi.string().optional().max(100),
  ctaUrl: Joi.string().uri().optional(),
  productId: Joi.string().optional(),
  categoryId: Joi.string().optional(),
  brandId: Joi.string().optional(),
  vendorId: Joi.string().optional(),
  offerCode: Joi.string().optional().max(50),
  offerText: Joi.string().optional().max(255),
  discountPercent: Joi.number().precision(2).min(0).max(100).optional(),
  discountAmount: Joi.number().precision(2).min(0).optional(),
  visibleToRoles: Joi.array().items(Joi.string()).optional(),
  visibleCities: Joi.array().items(Joi.string()).optional(),
  visibleStates: Joi.array().items(Joi.string()).optional(),
  visibleDevices: Joi.array().items(Joi.string()).optional(),
  startAt: Joi.date().optional(),
  endAt: Joi.date().optional(),
  displayOrder: Joi.number().integer().min(0).optional(),
  metadata: Joi.object().optional(),
  createdBy: Joi.string().optional(),
});

